FROM node:22-alpine

WORKDIR /app

COPY package.json ./
COPY pnpm-lock.yaml ./

RUN npm install -g pnpm

RUN pnpm install

# Copy the rest of the application source, excluding node_modules via .dockerignore
COPY . .

CMD ["pnpm", "run", "dev"]